# This file was generated by GoReleaser. DO NOT EDIT.
cask "huskwoot" do
  version "0.10.0"

  on_macos do
    on_intel do
      sha256 "93acdc03f02061cb39116ebb9a84e19e2f3c38d690fd3360f13fa9111ad0580b"
      url "https://github.com/anadale/huskwoot/releases/download/v#{version}/huskwoot_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "02ca8c309de0f370e8eade92a3fe89134fc8ffa51bb3d7cfa6ae9828999eb0a6"
      url "https://github.com/anadale/huskwoot/releases/download/v#{version}/huskwoot_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "628829efb5b162def8716c0c64632bdbf19b7e6577b4bad7c41a8bbd47aa04b8"
      url "https://github.com/anadale/huskwoot/releases/download/v#{version}/huskwoot_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "615f579f6dd75b49d5f6c55744d8d77c6ceef1cc71eb052a9181f94a65ba64b5"
      url "https://github.com/anadale/huskwoot/releases/download/v#{version}/huskwoot_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "huskwoot"
  desc "Personal promise and task tracker with Messengers/IMAP integration"
  homepage "https://github.com/anadale/huskwoot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "huskwoot"

  # No zap stanza required

end
