# This file was generated by GoReleaser. DO NOT EDIT.
cask "huskwoot" do
  version "0.6.0"

  on_macos do
    on_intel do
      sha256 "87b71b4fde63a8c0273538c0e097195f07553c15f8f4eac4541864c57cac1c8a"
      url "https://github.com/anadale/huskwoot/releases/download/v#{version}/huskwoot_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "3861b27ff465a577b6e7341798c36e9cbfa03832c10f92881e7bbd09f7e16e17"
      url "https://github.com/anadale/huskwoot/releases/download/v#{version}/huskwoot_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e1eb4a29670f72cc7e86b7f219d8902f18403ef3a70bb8d73de004a0860fadcb"
      url "https://github.com/anadale/huskwoot/releases/download/v#{version}/huskwoot_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "93e992cca80e3873981873dceba6ab06c74193bc249c4b6a7d3e6a216d49e00a"
      url "https://github.com/anadale/huskwoot/releases/download/v#{version}/huskwoot_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "huskwoot"
  desc "Personal promise and task tracker with Messengers/IMAP integration"
  homepage "https://github.com/anadale/huskwoot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "huskwoot"

  # No zap stanza required

end
