# This file was generated by GoReleaser. DO NOT EDIT.
cask "huskwoot" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "6c9f8635c3fa972654dc0afb3f2dc66fcb65b2ccbcb7517930c03ccfe17950ac"
      url "https://github.com/anadale/huskwoot/releases/download/v#{version}/huskwoot_#{version}_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "27c31b4e0c8cdac8b9f30a23bf53ed99f9bd018d5fb913402dd35b584a95d879"
      url "https://github.com/anadale/huskwoot/releases/download/v#{version}/huskwoot_#{version}_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "26925188e47df86e24d7b7d256bae0651497283598eee235318f3cb49df8816e"
      url "https://github.com/anadale/huskwoot/releases/download/v#{version}/huskwoot_#{version}_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "90bf862f9139f9ccda9eee5a97447f126a6a4e1b9489d771e9c134e3b1e2b0f7"
      url "https://github.com/anadale/huskwoot/releases/download/v#{version}/huskwoot_#{version}_Linux_arm64.tar.gz"
    end
  end

  name "huskwoot"
  desc "Personal promise and task tracker with Messengers/IMAP integration"
  homepage "https://github.com/anadale/huskwoot"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "huskwoot"

  # No zap stanza required

end
